version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: cvtheque_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
